apiVersion: v1
kind: pod
metadata:
  name: rest
  labels:
    app: rest
spec:
  containers:
    - name: bhanuprata9013/rest
      image: bhanuprata9013/rest
      ports:
        - containerPort: 9090
    
